#! /usr/bin/env bash
## Created by Lili Niu (lili.niu.ln1@roche.come)
## Created on 9/11/18
## This script is to take vcf file generated by Jian Li's Ruby scprit using jason variant input
## Then create g.name and use transvarto get all possible transcript with c.name and p.name using transvar ganno

filename="$1"
jax_pname_list=""
op_file=$filename".alltrans.txt"
unmap_file=$filename".unmap.txt"
log_file=$filename".alltrans.log"
echo -e "Input file:\t"$filename
echo -e "Output file:\t"$op_file
echo -e "Unmapped file:\t"$unmap_file
echo -e "Log file:\t"$log_file
echo -e '-------------'
> $op_file
> $unmap_file
> $log_file
while read -r line
do
    info=(${line///})
    chr=${info[0]}
    if [[ $chr == *"chr"* ]]; then
	start=${info[1]}
	end=$[${#info[3]}+$start-1]
	jax_pname=${info[2]}
	if [[ $jax_pname_list == *"$jax_pname"* ]]; then
	    echo -e $jax_pname" already checked" >>$log_file
	else
	    echo $jax_pname
	    #add jax_name to jax_name_list
	    jax_pname_list=$jax_pname_list" "$jax_pname
	    ref=${info[3]}
	    alt=${info[4]}
	    gname=$chr":g."$start"_"$end"delins"$alt
	    ##Step3: Use g.name to get all possible transcript with c.name and p.name 
	    ganno="transvar ganno -i $gname --ensembl >ganno.txt"
	    echo -e "\t"$ganno >>$log_file
	    transvar ganno -i $gname --ensembl >ganno.txt
	    pname_list=""
	    while read -r gline
	    do
		info2=(${gline// /:})
		##Step3.1: Transcrip need to be protein coding
		if [[ ${info2[1]} == *"protein_coding"* ]]; then
		    ##Step3.2: Get transcript and p.name
		    tx=${info2[1]%:*}
		    pname=${info2[4]#*/*/}
		    if [[ $pname == *"p."* ]]; then
			pname_list=$pname_list","$tx"("$pname")"
		    fi
		fi
	    done <"ganno.txt"
	    if [[ ! -z $pname_list ]]; then
		pname_list="${pname_list:1}"
		echo -e "\t"$jax_pname'\t'$gname'\t'$pname_list
		echo -e "\t"$jax_pname'\t'$gname'\t'$pname_list >>$log_file
		echo -e $jax_pname'\t'$gname'\t'$pname_list >> $op_file
	    else
		##if all transcript(s) has no p.name, add this varaint to unmap file
		echo -e "\t"$jax_pname"\t"$gname" is added to "$unmap_file
		echo -e "\t"$jax_pname"\t"$gname" is added to "$unmap_file>>$log_file
		echo -e $jax_pname"\t"$gname >>$unmap_file
		
	    fi
	fi
    fi
done <"$filename"

echo -e "_________"
echo -e "Output file:\t"$op_file
echo -e "Unmapped file:\t"$unmap_file
echo -e	"Log file:\t"$log_file
rm "ganno.txt"
